avoid repetition of content in incident response plan
Polpetta/SecurityAndRiskManagementNotes pull request #113
Opened 2017-08-11 15:01 UTC by herrBez

**Reference to the issue (_mandatory_)**: closes #
Con questo commit si evita di ripetere 3 volte gli step dell'incident response plan. 
addirittura si potrebbe evitare di ripeterlo due volte e mergiare direttamente la descrizione breve con quella lunga. 

**Description**

2017-08-12 09:57 UTC, mzanella approved these changes
Per me ci sta la descrizione breve e poi quella dettagliata

2017-08-12 10:06 UTC, herrBez commented
Si ieri ci avevo pensato meglio anche io e ci sta così come è nel commit 😁

2017-08-14 07:51 UTC, Polpetta requested changes
Non mi trovi d'accordo. Siccome per le domande che fa il prof 90% ti chiede di elencare i punti di un certo argomento, cancellare la lista puntata che è utile invece da sapere a memoria non ha senso. Qui ci sta che sia ripetuta.

2017-08-14 12:05 UTC, mzanella commented
Però sarebbe triplicata non ripetuta

2017-08-14 14:03 UTC, Polpetta commented
Mergia una delle spiegazioni nella lista puntata secondo me, è più chiaro
che son punti rispetto a una serie di paragrafi/sezioni

Il 14 ago 2017 14:05, "mzanella" <notifications@github.com> ha scritto:

> Però sarebbe triplicata non ripetuta
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/Polpetta/SecurityAndRiskManagementNotes/pull/113#issuecomment-322172902>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFp0907ixuL6AUc-NKzDaUSLVnzeeCvwks5sYDgagaJpZM4O0xVY>
> .
>

2017-08-14 14:24 UTC, Polpetta approved these changes

2017-08-14 14:24 UTC, merged