Proposal of improvement of section 15.2.2.1 to solve issue #114:
Polpetta/SecurityAndRiskManagementNotes pull request #142
Opened 2017-08-16 16:35 UTC by herrBez

Translated title: Challenges --> Sfide
Add specialized paragraph about Management buy-in
Add list of challenges

**Reference to the issue (_mandatory_)**: closes #114 

**Description**

2017-08-17 07:10 UTC, mzanella approved these changes

2017-08-18 08:40 UTC, Polpetta requested changes
A parte la modifica alle virgolette il resto va bene

2017-08-18 08:40 UTC, Polpetta commented on res/sections/31-Les06062017.tex
> +l'incident response plan. Questa soluzione ``a costo zero``
Riesci a mettere le `''` alla fine di `a costo zero`? Altrimenti vengono le virgolette storte e su tutto il resto del testo seguono il [pattern inglese](http://guitex.org/home/en/forum/5-tex-e-latex/14184-virgolette#14185)

2017-08-18 08:44 UTC, herrBez commented on res/sections/31-Les06062017.tex
> +l'incident response plan. Questa soluzione ``a costo zero``
ok

2017-08-18 08:46 UTC, herrBez commented
Fatto

2017-08-18 09:01 UTC, Polpetta approved these changes
lgtm

2017-08-18 09:01 UTC, merged