Major change in section 7.6.3
Polpetta/SecurityAndRiskManagementNotes pull request #153
Opened 2017-08-17 15:48 UTC by herrBez

**Reference to the issue (_mandatory_)**: closes #101 

**Description**
Sistemata la struttura del capitolo sul campionamento + Aggiunte descrizioni per chiarire la parte sul campionamento e alcuni tipi di campionamenti 

La struttura e le descrizioni sono state prese dal CISA review manual (quello citato dal prof per intenderci). 

Ho cercato di chiarire substantive testing e compliance testing rendendo più chiaro che si trattava di esempi. Usata la traduzione test sostanziale per tradurre substantive testing perchè rende più l'idea.

È un cambiamento abbastanza grande quindi potete anche rifiutarlo o dirmi cosa tenere (purtroppo ho fatto un solo commit perchè ero preso :sweat_smile:

2017-08-17 16:24 UTC, mzanella requested changes
*Errori grammaticali:*
- [ ] precudono -> precludono
- [ ] sottinsieme -> sottoinsieme

*Dubbi*
- [ ] C'è scritto:
```
Il vantaggio di questo approccio è che si perde la rappresentatività del campione statistico, 
ma si troveranno delle evidenze su ciò che si sta effettivamente cercando.
```



  Ma è davvero un vantaggio?

2017-08-17 17:12 UTC, herrBez commented
Grazie per le osservazioni @mzanella . Dimmi se adesso va meglio :smile:

2017-08-17 18:52 UTC, Polpetta commented
Domani ci butto un'occhiata!

Il 17 ago 2017 18:25, "mzanella" <notifications@github.com> ha scritto:

> *@mzanella* requested changes on this pull request.
>
> *Errori grammaticali:*
>
>    - precudono -> precludono
>    - sottinsieme -> sottoinsieme
>
> *Dubbi*
>
>    - C'è scritto:
>
>       Il vantaggio di questo approccio è che si perde la rappresentatività del campione statistico, ma si
>       troveranno delle evidenze su ciò che si sta effettivamente cercando.
>
> Ma è davvero un vantaggio?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/Polpetta/SecurityAndRiskManagementNotes/pull/153#pullrequestreview-56980819>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFp09327rv4vMNWutg_yi2YzlcKGqAeLks5sZGlTgaJpZM4O6dQC>
> .
>

2017-08-18 08:50 UTC, mzanella approved these changes

2017-08-18 08:54 UTC, Polpetta requested changes
Ottima riscrittura, ho trovato solo piccole robe che non vanno bene ma il contenuto è ottimo! Grande approfondimento 👍

2017-08-18 08:54 UTC, Polpetta commented on res/sections/22-Les12042017.tex
> +"i controlli sono presenti e eseguiti in maniera consistente?"}.
Metti le virgolette ` `` ` e `''` rispettivamente a inizio e fine :D

2017-08-18 08:54 UTC, Polpetta commented on res/sections/22-Les12042017.tex
> +\paragraph*{Esempio di Controllo:} il software in produzione è controllato?
Siamo sicuri che siano esempi? Boh io avevo capito che fossero tipo cose da fare

2017-08-18 08:54 UTC, Polpetta commented on res/sections/22-Les12042017.tex
> +\paragraph*{Esempio di Audit:} la sezione finanziaria sulle vendite è accurata?
Come sopra

2017-08-18 08:54 UTC, Polpetta commented on res/sections/23-Les18042017.tex
> +dell'unstratified mean per unit.
Forse andrebbe in corsivo `unstratified mean per unit` in quanto è in inglese 😅

2017-08-18 08:59 UTC, herrBez commented on res/sections/22-Les12042017.tex
> +\paragraph*{Esempio di Controllo:} il software in produzione è controllato?
Bella domanda.. :sweat_smile:

2017-08-18 09:02 UTC, herrBez commented on res/sections/22-Les12042017.tex
> +\paragraph*{Esempio di Audit:} la sezione finanziaria sulle vendite è accurata?
Bella domanda. 
![image](https://user-images.githubusercontent.com/6976484/29451886-92cc285c-8404-11e7-9045-f45af417d79d.png)
Qua mi sembra di capire che sia un esempio

2017-08-18 09:03 UTC, herrBez commented on res/sections/22-Les12042017.tex
> +\paragraph*{Esempio di Controllo:} il software in produzione è controllato?
Anche qua sembrano esempi ma non sono sicuro:
![image](https://user-images.githubusercontent.com/6976484/29451952-dd84d150-8404-11e7-98d0-98d90ba3e3a0.png)

2017-08-18 09:10 UTC, Polpetta commented on res/sections/22-Les12042017.tex
> +\paragraph*{Esempio di Audit:} la sezione finanziaria sulle vendite è accurata?
Ok allora, teniamo così 👍

2017-08-18 09:10 UTC, Polpetta approved these changes

2017-08-18 09:10 UTC, merged