Add definition of long-haul network diversity
Polpetta/SecurityAndRiskManagementNotes pull request #175
Opened 2017-08-20 21:17 UTC by herrBez

**Reference to the issue (_mandatory_)**: closes #

**Description**

2017-08-21 08:42 UTC, mzanella commented on res/sections/13-Les08032017.tex
> +    ridondanti;
Sei sicuro che voglia dire questo? Perchè mi sembra che `ricorrere a network provider ridondanti` sia il `l'alternative routing` in generale

2017-08-21 08:47 UTC, herrBez commented on res/sections/13-Les08032017.tex
> +    ridondanti;
No.. Allora secondo le slide 
![image](https://user-images.githubusercontent.com/6976484/29510961-e7c8b388-865d-11e7-96e5-bcf3397a65e0.png)
mentre per l'ISACA review Manual 
![image](https://user-images.githubusercontent.com/6976484/29511002-059b6806-865e-11e7-8a9c-d0f2e8d0104b.png)

2017-08-21 14:19 UTC, Polpetta commented
Che si fa?

2017-08-21 14:37 UTC, herrBez commented
Io aspettavo una risposta da @mzanella riguardo al commento e poi deciderei. Per ora su carta ho scritto solo `> 1 network provider` come c'è scritto nelle slide

2017-08-21 15:26 UTC, mzanella commented
Non so cosa dire sinceramente... Io il long haul l'avevo inteso come un modo diverso per avere internet e non come l'avere più ISP:sweat_smile:

2017-08-23 09:26 UTC, mzanella commented
@Polpetta io non sono sicuro sinceramente della definizione di long haul anche per questo per esempio https://en.wikipedia.org/wiki/Long-haul_communications se siete sicuri mergiate pure

2017-08-23 14:57 UTC, herrBez commented
Secondo me la deffinizione a cui si riferisce Di Pietro è quella dello screen shot perché è presa dal CISA review manual, ma non saprei come riassumerla e tradurla decentemente

2017-08-23 16:04 UTC, herrBez commented
Ci aggiungiamo la label prof?

2017-08-23 16:16 UTC, mzanella commented
Yes

On 23 Aug 2017 6:04 p.m., "herrBez" <notifications@github.com> wrote:

> Ci aggiungiamo la label prof?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Polpetta/SecurityAndRiskManagementNotes/pull/175#issuecomment-324383128>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMA0JtedndNsN0V7wY9Uyon8LjHlyWlYks5sbE17gaJpZM4O8u5H>
> .
>

2017-08-23 19:45 UTC, herrBez commented
Cosa scriviamo al prof???

2017-08-23 20:17 UTC, Polpetta commented
Gli dici che stavamo ripassando insieme e che non siamo riusciti a trovare
una definizione che descrivesse appieno questo termine!:)

Il 23 ago 2017 21:45, "herrBez" <notifications@github.com> ha scritto:

> Cosa scriviamo al prof???
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Polpetta/SecurityAndRiskManagementNotes/pull/175#issuecomment-324442176>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFp090v2EkIErFJT9ld5rIWIQEYQRiYRks5sbIFDgaJpZM4O8u5H>
> .
>

2017-08-28 09:21 UTC, Polpetta commented
Che ne facciamo di questa?

2017-08-28 10:07 UTC, herrBez commented
Io aspetterei la risposta del prof. o riproverei a guardare il manuale..

2017-08-29 09:08 UTC, mzanella commented
Mettiamo quanto scritto dal prof allora?
```
Long haul diversity: È la diversificazione dei fornitori di connettività su lunghe distanze assicurandosi che i tratti fisici impiegati siano effettivamente differenti, infatti è possibile che piu' fornitori condividano lo stesso mezzo dfisico (come nel caso della fibra). Tra i principali mezzi trasmissivi a lunga distanza ci sono i circuiti T-1.
```

2017-08-29 09:09 UTC, herrBez commented
Ottimo (coincide al manuale).

2017-08-29 09:43 UTC, mzanella commented
Top vado allora

2017-08-29 10:00 UTC, Polpetta commented
Ottimo, occhio al typo in `dfisico`

2017-08-29 11:51 UTC, mzanella commented
@herrBez @Polpetta se mi date l'ok mergio

2017-08-30 08:06 UTC, Polpetta requested changes
Ti sei dimenticato un accento, per il resto va bene 👍

2017-08-30 08:06 UTC, Polpetta commented on res/sections/13-Les08032017.tex
> +    siano effettivamente differenti, infatti èpossibile che piu' fornitori
`più` non `piu'`

2017-08-30 13:32 UTC, merged

2017-08-31 08:10 UTC, Polpetta commented
🙏 Pensavo non si sarebbe mai mergiata questa cosa

2017-09-02 08:25 UTC, herrBez commented
:heart: