197 ruoli risk management
Polpetta/SecurityAndRiskManagementNotes pull request #239
Opened 2017-08-27 08:58 UTC by mzanella

**Reference to the issue (_mandatory_)**: closes #197 

**Description**

2017-08-27 10:41 UTC, herrBez requested changes
Mi sembra che il Chief Information Officer abbia un ruolo distinto dal Information Securitymanager che penso sia il CISO. 

Inoltre il CISO non alloca le risorse ecc. ma quello è il Governance and Senior Management

2017-08-27 10:50 UTC, mzanella commented
Ho aggiunto l'IS manager ma sinceramente non so cosa scrivere su CIO/CISO

2017-08-27 14:21 UTC, Polpetta submitted a review, later dismissed
👌  Per me è ok, mancano le correzioni di @herrBez il resto mi pare ci sia

2017-08-27 14:36 UTC, mzanella commented
Ho già fatto le correzioni di @herrBez Basta aggiungere quello che fanno CIO e CISO ma io non lo so:sweat_smile:

2017-08-28 06:37 UTC, herrBez commented
Ragazzi ma le slide le potete guardare anche voi :sweat_smile:

2017-08-28 06:52 UTC, herrBez commented
![image](https://user-images.githubusercontent.com/6976484/29762312-333eb8ec-8bce-11e7-89dd-31b8680c6604.png)

Credo che abbia preso da qui le informazioni..

2017-08-28 08:06 UTC, herrBez approved these changes

2017-08-28 08:56 UTC, Polpetta commented
> Ragazzi ma le slide le potete guardare anche voi 

Non so leggere 🤷‍♂️

2017-08-28 09:03 UTC, Polpetta approved these changes
Per me va bene, ho aggiunto anche un acronimo così ora è proprio completo 👌

2017-08-28 09:04 UTC, herrBez approved these changes

2017-08-28 09:04 UTC, herrBez commented
@mzanella mergia pure se per te è ok!

2017-08-28 09:15 UTC, merged