211 consegna risultati audit
Polpetta/SecurityAndRiskManagementNotes pull request #252
Opened 2017-08-28 09:45 UTC by mzanella

**Reference to the issue (_mandatory_)**: closes #211

**Description**

2017-08-29 09:35 UTC, herrBez requested changes
sistemare la frase sui "ai manager di basso livello" ecc. 

Ottimo, per me si potrebbe anche eliminare la figura, voi cosa ne pensate @mzanella @Polpetta

2017-08-29 09:42 UTC, mzanella commented
Io la figura la lascerei...

2017-08-29 09:43 UTC, mzanella commented
Cosa cmabieresti della frase?

2017-08-29 09:50 UTC, Polpetta commented on res/sections/23-Les18042017.tex
> +ciò che cerco mi fermo (e.g. se i primi 20 elementi hanno zero errori allora mi
Ma sono 80 caratteri?

2017-08-29 09:53 UTC, Polpetta commented
Io la immagine la lascerei, mi aiuta a chiarire le idee!

2017-08-29 09:56 UTC, Polpetta requested changes
Io cambierei quella parte così

2017-08-29 09:56 UTC, Polpetta commented on res/sections/23-Les18042017.tex
> +  \item ai manager di basso livello deve essere riportato il materiale
Io riscriverei così:
```tex
i \textbf{manager di basso livello}. A loro deve essere riportanto [...]
```

2017-08-29 09:56 UTC, Polpetta commented on res/sections/23-Les18042017.tex
> +  \item ai manager di alto livello invece deve essere consegnata la parte più
anche qui:
```tex
i \textbf{manager di alto livello}. A loro dev'essere consegnata [...]
```

2017-08-29 10:00 UTC, mzanella commented on res/sections/23-Les18042017.tex
> +ciò che cerco mi fermo (e.g. se i primi 20 elementi hanno zero errori allora mi
![image](https://user-images.githubusercontent.com/12596262/29815626-9e7037ba-8cb1-11e7-8323-44eacdb640c5.png)
79 dice sublime

2017-08-29 10:04 UTC, mzanella commented on res/sections/23-Les18042017.tex
> +  \item ai manager di basso livello deve essere riportato il materiale
ok

2017-08-29 10:04 UTC, mzanella commented on res/sections/23-Les18042017.tex
> +  \item ai manager di alto livello invece deve essere consegnata la parte più
ok

2017-08-29 10:06 UTC, Polpetta commented on res/sections/23-Les18042017.tex
> +ciò che cerco mi fermo (e.g. se i primi 20 elementi hanno zero errori allora mi
👌 bravo figliolo

2017-08-29 10:07 UTC, Polpetta submitted a review, later dismissed
Direi che è ok adesso: la lista puntata è più diretta! 😊

2017-08-29 11:46 UTC, mzanella commented
@herrBez ping

2017-09-02 07:40 UTC, herrBez commented
Ho sistemato due robette date un'occhiata ^^ . In caso accettate e mergiate

2017-09-02 07:43 UTC, herrBez approved these changes

2017-09-02 09:47 UTC, Polpetta approved these changes

2017-09-02 09:48 UTC, merged