Fraud fix
Polpetta/SecurityAndRiskManagementNotes pull request #38
Opened 2017-08-07 12:50 UTC by herrBez

**Reference to the issue (if any)**: #32 

**Description**

2017-08-07 13:32 UTC, mzanella commented
Per me è ok. Farei controllare anche a @Polpetta però.

2017-08-07 14:01 UTC, Polpetta requested changes

2017-08-07 14:01 UTC, Polpetta commented on res/sections/11-Les01032017.tex
> +Le veri frodi, quelle che sono costate molto anche a livello di immagine, sono
Ma qui non è al femminile?

2017-08-07 14:01 UTC, Polpetta commented on res/sections/11-Les01032017.tex
> +Media per sesso: 250 \euro uomini contro 120 \euro donne.\\
Se non metti le `{}` dopo il comando dell'euro vedrai che non ti mette lo spazio e quindi viene tutto appiccicato.

2017-08-07 14:01 UTC, Polpetta commented
@mzanella se a te va bene fai `approve changes`

2017-08-07 14:35 UTC, mzanella commented on res/sections/11-Les01032017.tex
> +Le veri frodi, quelle che sono costate molto anche a livello di immagine, sono
È giusto al femminile

2017-08-07 15:19 UTC, Polpetta commented on res/sections/11-Les01032017.tex
> +Le veri frodi, quelle che sono costate molto anche a livello di immagine, sono
Quindi dovrebbe essere ver _e_, non ver _i_

2017-08-07 16:50 UTC, herrBez commented on res/sections/11-Les01032017.tex
> +Media per sesso: 250 \euro uomini contro 120 \euro donne.\\
Ciao, ma io quello non l'ho toccato ^^.

2017-08-07 16:50 UTC, herrBez commented on res/sections/11-Les01032017.tex
> +Le veri frodi, quelle che sono costate molto anche a livello di immagine, sono
Si vere, ma io non ho modificato queste frasi.

2017-08-08 15:14 UTC, mzanella approved these changes
Ho sistemato le due cose che diceva @Polpetta quindi dovrebbe andare bene ora

2017-08-08 15:40 UTC, Polpetta commented
Non posso guardare ora, son via, ma se non è stata modificata altra roba e
avete corretto la roba che non andava bene allora è ok

Il 08 ago 2017 17:15, "mzanella" <notifications@github.com> ha scritto:

> *@mzanella* approved this pull request.
>
> Ho sistemato le due cose che diceva @Polpetta
> <https://github.com/polpetta> quindi dovrebbe andare bene ora
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Polpetta/SecurityAndRiskManagementNotes/pull/38#pullrequestreview-54971103>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFp09-OD99iiL-T_AOr-Ub_mU5hdzAmtks5sWHtPgaJpZM4OvZLF>
> .
>

2017-08-08 17:20 UTC, merged